name: beans
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  gradient_app_bar: ^0.1.3
  gradient_widgets: ^0.5.1
  percent_indicator: ^2.1.6
  gen_lang: ^0.1.3
  sqflite: ^1.3.0
  path: ^1.7.0
  provider: ^4.3.2+1
  supercharged: ^1.10.0
  date_format: ^1.0.9
  flutter_circular_chart: ^0.1.0
  backdrop: ^0.4.7
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ic_empty_list.svg
    - assets/ic_time.svg
    - assets/ic_home.svg
    - assets/ic_pin.svg
    - assets/ic_god.png
    - assets/ic_money.svg
    - assets/ic_human_rights.svg
    - assets/ic_quote.svg
    - assets/ic_plus.svg
    - assets/ic_myself.png
    - assets/ic_arrow_next.svg
    - assets/ic_minus.svg
    - assets/ic_add.svg
    - assets/ic_confess_done.svg
    - assets/ic_calendar.svg
    - assets/ic_close.svg
    - assets/ic_confession.svg
    - assets/ic_bean.svg
    - assets/ic_snowman.svg
    - assets/ic_black_bean.svg
    - assets/ic_switch_active_blue.svg
    - assets/ic_other_guys.png
    - assets/ic_health.svg
    - assets/ic_switch_inactive.svg
    - assets/ic_sucess.svg
    - assets/ic_switch_active.svg
    - assets/tooltip.png
    - assets/ic_snow_png.png
    - assets/ic_white_bean.svg
    - assets/background_god_png.png
    - assets/ic_logo.svg
    - assets/ic_more.svg
    - assets/ic_congratulation1.svg
    - assets/ic_congratulation.svg
    - assets/ic_close_gradient.png
    - assets/ic_expired.png
    - assets/ic_community.svg
    - assets/ic_family.svg
    - assets/ic_god_vs_me.svg
    - assets/ic_god_word.svg
    - assets/ic_religion.svg
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
